### ISSUE TITLE
Wrong Field 43 check for Structured Securities vs Funds 

### ISSUE THREAD

**Issue by plidauer** [karlkauc/FundsXML-EMT-Converter#6]
Hi, 

please refer to my change suggestion I created last week:

"According to our EMT File Definition (v1.0) Field 43 "07010_Structured_Securities_Quotation" is set mandatory/conditional for Structured Securities. Your expression evaluates to true iff it is set, but then you create a Fund node and not a StructuredSecurity node. Therefore I propose the following change. "

https://github.com/karlkauc/FundsXML-EMT-Converter/compare/master...plidauer:patch-1

Many thanks!
Philipp

**Comment by karlkauc** [comment]
done.
